language: node_js
node_js: stable
cache: yarn


# Use macOS 10.12: https://docs.travis-ci.com/user/languages/objective-c/
matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode9.1
      env: TEST_SUITE=test-build
    - os: linux
      dist: trusty
      env: TEST_SUITE=lint
    - os: linux
      dist: trusty
      env: TEST_SUITE=test-build

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew install ripgrep
      brew install watchman
    else
      curl -LO https://github.com/BurntSushi/ripgrep/releases/download/0.9.0/ripgrep_0.9.0_amd64.deb
      sudo dpkg -i ripgrep_0.9.0_amd64.deb
      git clone https://github.com/facebook/watchman.git
      cd watchman
      ./autogen.sh
      ./configure
      make
      sudo make install
    fi
  - rg --version
  - watchman --version
  - curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
      tar xzf nvim-macos.tar.gz
      export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-osx64/bin"
    else
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
      tar xzf nvim-linux64.tar.gz
      export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-linux64/bin"
    fi
  - echo $PATH
  - nvim --version

install:
  - yarn install

script:
  - export NVIM_COC_LOG_LEVEL=debug
  - export NODE_ENV=test
  - yarn global add codecov
  - yarn global add typescript
  - yarn $TEST_SUITE

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: never
    on_cancel: never
    on_error: never
