name: coc.nvim CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10, 12]
        os: [ubuntu-latest, macos-latest]

    env:
      NODE_ENV: test

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: |
          curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
      - uses: actions/checkout@v1
      - name: yarn install
        run: |
          yarn global add typescript
          yarn
      - name: yarn lint
        run: yarn lint
      - name: yarn test
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
          tar xzf nvim-linux64.tar.gz
          export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-linux64/bin"
          nvim --version
          yarn test-build
        env:
          NODE_ENV: test
